### ISSUE TITLE
[Feature] - Smaller snapshot size

### ISSUE THREAD

**Issue by filipetoscano** [vultr/packer-plugin-vultr#107]
**Is your feature request related to a problem? Please describe.**
Taking a snapshot of an instance with a 25 GB disk yields a 25 GB snapshot even if only a fraction of the disk is being used -- which results in:

* High time to take a snapshot (not major, since new base images aren't created all the time);
* Takes time to spin new instances (annoying, since the purpose of using packer+terraform was to speed up node spin-up)

**Describe the solution you'd like**
That `packer-builder-vultr` would yield smaller snapshot images.

**Describe alternatives you've considered**
Not using packer: moving our shell scripts to provisioning stage after instance spin up.

**Comment by ddymko** [comment]
@filipetoscano 

This is something that could be addressed by zeroing out the unused space on the volume with a shell provisioner in your packer setup
https://www.packer.io/docs/provisioners/shell

**Comment by filipetoscano** [comment]
Hi @ddymko !

The remark on snapshot is with regards to a newly spun up instance (by packer) -- how could the virtual disk grow to the full 25 GB by running a handful of scripts?

Do you have any automated recipe for zeroing out unused space?

In order to use zerofree, you need to reboot into a read-only `/dev/vda1` -- at least I couldn't do a live remount, not even after stopping services/killing processes which were actively writing to the partition.

**Comment by ddymko** [comment]
You could have a shell provisioner run something such as 

```
 "dd if=/dev/zero of=/EMPTY bs=1M | true",
 "rm -f /EMPTY",
 "sync"
```
