### ISSUE TITLE
Cannot build Arch linux image

### ISSUE THREAD

**Issue by man0v** [vultr/packer-plugin-vultr#195]
**Describe the bug**
Packer build of arch linux image is impossible due to nmcli/cloud-init issue.

**To Reproduce**

Try to build vanilla.pkr.hcl.txt(attached)
`mv vanilla.pkr.hcl{.txt,}`
`packer init vanilla.pkr.hcl`
`packer build vanilla.pkr.hcl`

**Expected behavior**
A clean build(no provisioners being applied) and a snapshot being created.

**Screenshots**
![screen1](https://user-images.githubusercontent.com/3229403/172577404-28e52cae-7a51-4c51-ba5f-0ca0b699da96.png)
![screen2](https://user-images.githubusercontent.com/3229403/172577423-7f77a9f7-2aac-41e4-a280-8f521f739029.png)

**Desktop (please complete the following information where applicable:**

OS: Mac OS X 12.4
Language Version N/A
Browser N/A
Version packer 1.8.1 and vultr-plugin 2.4.5
**Additional context**

After doing some debugging I found the error attached on the screenshot - whatever cloud-init is doing is causing network manager to fail to acquire IP and as a result the VM is unavailable....

Arch linux works fine if I provision using the web console, so the problem has to do with whatever packer is injecting as cloud-init(at least to my understanding).

I get some level of success when I manually run on the vm `nmcli d connect enp1s0`, however, even though I can connect via ssh, the command fails after a while and the network goes down again.

[vanilla.pkr.hcl.txt](https://github.com/vultr/packer-plugin-vultr/files/8860100/vanilla.pkr.hcl.txt)

**Comment by optik-aper** [comment]
I was able to build arch images when I was testing the SDK yesterday but I'm seeing the same issues you've reported here so we'll have to take another look.  Thanks for reporting this.

**Comment by optik-aper** [comment]
I haven't been having this issue with the latest images and cloud-init updates.
