### ISSUE TITLE
[Feature] - Add to official Packer builder list

### ISSUE THREAD

**Issue by binaryfire** [vultr/packer-plugin-vultr#24]
Hi guys,

Are there any plans to partner with Hashicorp to get Vultr added as an official builder (rather than a third party / community one)? Linode, DO and Hetzner are all officially supported. Would be great to see Vultr there too.

**Comment by ddymko** [comment]
Hey there,

We actually opened up a PR to packer to get us merged in as an official provider a while back.

However, packer is currently changing how they will be handling this provider plugins so we haven’t been able to get merged in. At this point we are waiting for packer to release this new approach for provider plugins.

You can read a more detailed response from packer here:
https://github.com/hashicorp/packer/pull/8075

**Comment by binaryfire** [comment]
@ddymko Ah right, I see. Thanks for the quick reply and the info. Hopefully they release their new approach soon.

PS. I was also wondering if there is a size limit for images on Vultr? For example Linode limits them to 2GB

**Comment by ddymko** [comment]
With vultr v2.3.0 we now support `packer init` functionality which doesn't require pulling binaries by hand

#111
